//
// Created by Андрей Болоцкий on 15.08.2023.
//
#include<pqxx/pqxx>
#include<iostream>
#include<fstream>
int main(){
    std::ifstream input("../database.config");
    std::string connectionString;
    std::getline(input, connectionString);
    try {
        pqxx::connection connection(connectionString);
        pqxx::work worker{connection};
        worker.exec("CREATE TABLE \"users\" (\n"
            "\t\"id\" serial NOT NULL,\n"
            "\t\"email\" character varying(64) NOT NULL UNIQUE,\n"
            "\t\"password\" character varying(64) NOT NULL,\n"
            "\tCONSTRAINT \"users_pk\" PRIMARY KEY (\"id\")\n"
            ") WITH (\n"
            "  OIDS=FALSE\n"
            ");\n"
            "\n"
            "\n"
            "\n"
            "CREATE TABLE \"users_languages_relationship\" (\n"
            "\t\"user_id\" bigint NOT NULL,\n"
            "\t\"language_from_id\" bigint NOT NULL,\n"
            "\t\"language_to_id\" bigint NOT NULL,\n"
            "\t\"language_level_id\" bigint NOT NULL\n"
            ") WITH (\n"
            "  OIDS=FALSE\n"
            ");\n"
            "\n"
            "\n"
            "\n"
            "CREATE TABLE \"exercises\" (\n"
            "\t\"id\" serial NOT NULL,\n"
            "\t\"complexity\" bigint NOT NULL,\n"
            "\t\"exercise_type_id\" bigint NOT NULL,\n"
            "\t\"language_from_id\" bigint NOT NULL,\n"
            "\t\"language_to_id\" bigint NOT NULL,\n"
            "\t\"content\" jsonb NOT NULL,\n"
            "\tCONSTRAINT \"exercises_pk\" PRIMARY KEY (\"id\")\n"
            ") WITH (\n"
            "  OIDS=FALSE\n"
            ");\n"
            "\n"
            "\n"
            "\n"
            "CREATE TABLE \"courses\" (\n"
            "\t\"id\" serial NOT NULL,\n"
            "\t\"name\" character varying(32) NOT NULL,\n"
            "\t\"lessons_count\" bigint NOT NULL,\n"
            "\t\"type_of_course\" bigint,\n"
            "\t\"language_level_id\" bigint NOT NULL,\n"
            "\t\"language_to\" bigint NOT NULL,\n"
            "\t\"language_from\" bigint NOT NULL,\n"
            "\tCONSTRAINT \"courses_pk\" PRIMARY KEY (\"id\")\n"
            ") WITH (\n"
            "  OIDS=FALSE\n"
            ");\n"
            "\n"
            "\n"
            "\n"
            "CREATE TABLE \"users_courses_relationship\" (\n"
            "\t\"user_id\" bigint NOT NULL,\n"
            "\t\"course_id\" bigint NOT NULL,\n"
            "\t\"user_lesson_index\" bigint NOT NULL\n"
            ") WITH (\n"
            "  OIDS=FALSE\n"
            ");\n"
            "\n"
            "\n"
            "\n"
            "CREATE TABLE \"lessons\" (\n"
            "\t\"id\" serial NOT NULL,\n"
            "\t\"name\" character varying(32) NOT NULL,\n"
            "\tCONSTRAINT \"lessons_pk\" PRIMARY KEY (\"id\")\n"
            ") WITH (\n"
            "  OIDS=FALSE\n"
            ");\n"
            "\n"
            "\n"
            "\n"
            "CREATE TABLE \"courses_lessons_relationship\" (\n"
            "\t\"course_id\" bigint NOT NULL,\n"
            "\t\"lesson_index\" bigint NOT NULL,\n"
            "\t\"lesson_id\" bigint NOT NULL\n"
            ") WITH (\n"
            "  OIDS=FALSE\n"
            ");\n"
            "\n"
            "\n"
            "\n"
            "CREATE TABLE \"lessons_exercises_relationship\" (\n"
            "\t\"lesson_id\" bigint NOT NULL,\n"
            "\t\"exercise_id\" bigint NOT NULL,\n"
            "\t\"exercise_index\" bigint NOT NULL\n"
            ") WITH (\n"
            "  OIDS=FALSE\n"
            ");\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "ALTER TABLE \"users_languages_relationship\" ADD CONSTRAINT \"users_languages_relationship_fk0\" FOREIGN KEY (\"user_id\") REFERENCES \"users\"(\"id\");\n"
            "\n"
            "\n"
            "\n"
            "ALTER TABLE \"users_courses_relationship\" ADD CONSTRAINT \"users_courses_relationship_fk0\" FOREIGN KEY (\"user_id\") REFERENCES \"users\"(\"id\");\n"
            "ALTER TABLE \"users_courses_relationship\" ADD CONSTRAINT \"users_courses_relationship_fk1\" FOREIGN KEY (\"course_id\") REFERENCES \"courses\"(\"id\");\n"
            "\n"
            "\n"
            "ALTER TABLE \"courses_lessons_relationship\" ADD CONSTRAINT \"courses_lessons_relationship_fk0\" FOREIGN KEY (\"course_id\") REFERENCES \"courses\"(\"id\");\n"
            "ALTER TABLE \"courses_lessons_relationship\" ADD CONSTRAINT \"courses_lessons_relationship_fk1\" FOREIGN KEY (\"lesson_id\") REFERENCES \"lessons\"(\"id\");\n"
            "\n"
            "ALTER TABLE \"lessons_exercises_relationship\" ADD CONSTRAINT \"lessons_exercises_relationship_fk0\" FOREIGN KEY (\"lesson_id\") REFERENCES \"lessons\"(\"id\");\n"
            "ALTER TABLE \"lessons_exercises_relationship\" ADD CONSTRAINT \"lessons_exercises_relationship_fk1\" FOREIGN KEY (\"exercise_id\") REFERENCES \"exercises\"(\"id\");\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "\n"
            "");
        worker.commit();
        std::cout<<"creating tables ended correctly";
    }
    catch(std::exception& e){
        std::cout<<e.what();
    }
}